inventoryproject/dashboard/urls.py
from django.urls import path
from . import views
app_name = "dashboard"
urlpatterns = [
    path("", views.index, name="index"),
    path("staff/", views.staff, name="staff"),
    path("staff/detail/<int:pk>", views.staff_detail, name="staff_detail"),
    path("product/", views.product, name="product"),
    path("product/update/<int:pk>", views.product_update, name="product_update"),
    path("product/delete/<int:pk>", views.product_delete, name="product_delete"),
    path("order/", views.order, name="order"),
]

inventoryproject/inventoryproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("dashboard/", include("dashboard.urls")),
    path("", include("user.urls")),
    path(
        "password_reset/",
        auth_views.PasswordResetView.as_view(template_name="user/password_reset.html"),
        name="password_reset",
    ),
    path(
        "password_reset_done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="user/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "password_reset_confirm/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="user/password_reset_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "password_reset_complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="user/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]

inventoryproject/user/urls.py
from django.urls import path
from . import views as user_views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

app_name = "user"
urlpatterns = [
    path("register/", user_views.register, name="register"),
    path("profile/", user_views.profile, name="profile"),
    path("profile/update/", user_views.profile_update, name="profile-update"),
    path(
        "", auth_views.LoginView.as_view(template_name="user/login.html"), name="login"
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(template_name="user/logout.html"),
        name="logout",
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inventoryproject/templates/partials/base.html
{% load static %}
<!doctype html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js"></script>
        <link rel="stylesheet" href="{% static "/style.css" %}">
        <title>{% block title %}{% endblock %}</title>
    </head>
    <body>
        {% include 'partials/nav.html' %}
        {% block content %}{% endblock %}
        <!-- Optional JavaScript; choose one of the two! -->
        <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
        <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
        <!-- Option 2: Separate Popper and Bootstrap JS -->
        <!--
        <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>
        -->
    </body>
</html>

inventoryproject/templates/partials/nav.html
<nav class="navbar navbar-expand-lg navbar-info bg-info">
    {% if user.is_authenticated %}
        <div class="container">
            <a class="navbar-brand text-white" href="{% url "dashboard:index" %}">Inventory</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link text-white" href="{% url "dashboard:index" %}">Dashboard <span
                                class="sr-only">(current)</span></a>
                    </li>
                </ul>
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active">
                        <a class="nav-link text-white" href="{% url "user:profile" %}">{{ user.username }} Profile <span
                                class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" href="{% url "user:logout" %}">Logout</a>
                    </li>
                </ul>
    {% else %}
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active">
                        <a class="nav-link text-white" href="{% url "user:register" %}">Register <span
                                class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" href="{% url "user:login" %}">Login</a>
                    </li>
                </ul>
    {% endif %}
            </div>
        </div>
    </nav>

inventoryproject/templates/partials/topnav.html
<div class="container">
    <div class="row mt-4">
        <div class="col-md-4">
            <div class="card">
                <div class="card-header bg-info text-white">
                    Information
                </div>
                <div class="card-body">
                    <marquee behavior="" direction="">
                        <h3 class="my-4">This is the Information</h3>
                    </marquee>
                </div>
            </div>
        </div>
        <div class="col-md-8">
            <div class="card">
                <div class="card-header bg-info text-white">
                    Statistics
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-4">
                            <a class="text-decoration-none text-dark" href="{% url "dashboard:staff" %}">
                                <div class="card my-card shadow text-center p-3">
                                    <h4>Staff <i class="fas fa-users"></i></h4>
                                    <h3>{{ workers_count }}</h3>
                                </div>
                            </a>
                        </div>
                        <div class="col-md-4">
                            <a class="text-decoration-none text-dark" href="{% url "dashboard:product" %}">
                                <div class="card my-card shadow text-center p-3">
                                    <h4>Products <i class="fas fa-box"></i></h4>
                                    <h3>{{ products_count }}</h3>
                                </div>
                            </a>
                        </div>
                        <div class="col-md-4">
                            <a class="text-decoration-none text-dark" href="{% url "dashboard:order" %}">
                                <div class="card my-card shadow text-center p-3">
                                    <h4>Orders <i class="fas fa-shipping-fast"></i></h4>
                                    <h3>{{ orders_count }}</h3>
                                </div>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>