inventoryproject/dashboard/urls.py
from django.urls import path
from . import views
app_name = "dashboard"
urlpatterns = [
    path("", views.index, name="index"),
    path("staff/", views.staff, name="staff"),
    path("staff/detail/<int:pk>", views.staff_detail, name="staff_detail"),
    path("product/", views.product, name="product"),
    path("product/update/<int:pk>", views.product_update, name="product_update"),
    path("product/delete/<int:pk>", views.product_delete, name="product_delete"),
    path("order/", views.order, name="order"),
]

inventoryproject/inventoryproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("dashboard/", include("dashboard.urls")),
    path("", include("user.urls")),
    path(
        "password_reset/",
        auth_views.PasswordResetView.as_view(template_name="user/password_reset.html"),
        name="password_reset",
    ),
    path(
        "password_reset_done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="user/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "password_reset_confirm/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="user/password_reset_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "password_reset_complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="user/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]

inventoryproject/user/urls.py
from django.urls import path
from . import views as user_views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

app_name = "user"
urlpatterns = [
    path("register/", user_views.register, name="register"),
    path("profile/", user_views.profile, name="profile"),
    path("profile/update/", user_views.profile_update, name="profile-update"),
    path(
        "", auth_views.LoginView.as_view(template_name="user/login.html"), name="login"
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(template_name="user/logout.html"),
        name="logout",
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inventoryproject/dashboard/models.py
from django.db import models
from django.contrib.auth.models import User
CATEGORIES = (
    ('stationary' , 'stationary'),
    ('electronics' , 'electronics'),
    ('food' , 'food'),
    )
class Product(models.Model):
    name = models.CharField(max_length=100)
    category = models.CharField(max_length=20 , choices=CATEGORIES , null=True)
    quantity = models.PositiveIntegerField(null=True)
    def __str__(self):
        return f"{self.name} - {self.quantity}"
    class Meta:
        verbose_name_plural = 'Product'
class Order(models.Model):
    product = models.ForeignKey(Product , on_delete=models.CASCADE , null=True)
    staff = models.ForeignKey(User , on_delete=models.CASCADE , null=True)
    order_quantity = models.PositiveIntegerField(null=True)
    date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return f"{self.product} ordered by {self.staff.username}"
    class Meta:
        verbose_name_plural = 'Order'

inventoryproject/dashboard/forms.py
from django import forms
from .models import Product, Order
class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ["name", "category", "quantity"]
class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ["product", "order_quantity"]

inventoryproject/dashboard/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Product, Order
from .forms import ProductForm, OrderForm
from django.contrib.auth.models import User
from django.contrib import messages


@login_required
def index(request):
    orders = Order.objects.all()
    products = Product.objects.all()
    workers_count = User.objects.all().count()
    orders_count = orders.count()
    products_count = products.count()
    if request.method == "POST":
        form = OrderForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.staff = request.user
            instance.save()
            return redirect("dashboard:index")
    else:
        form = OrderForm()
    context = {
        "orders": orders,
        "products": products,
        "form": form,
        "workers_count": workers_count,
        "orders_count": orders_count,
        "products_count": products_count
    }
    return render(request, "dashboard/index.html", context)


@login_required
def staff(request):
    workers = User.objects.all()
    workers_count = workers.count()
    orders_count = Order.objects.all().count()
    products_count = Product.objects.all().count()
    print(workers_count)
    context = {
        "workers": workers,
        "workers_count": workers_count,
        "orders_count": orders_count,
        "products_count": products_count,
    }
    return render(request, "dashboard/staff.html", context)


@login_required
def staff_detail(request, pk):
    workers = User.objects.get(id=pk)
    context = {"workers": workers}
    return render(request, "dashboard/staff_detail.html", context)


@login_required
def product(request):
    items = Product.objects.all()
    workers_count = User.objects.all().count()
    orders_count = Order.objects.all().count()
    products_count = items.count()
    if request.method == "POST":
        form = ProductForm(request.POST)
        if form.is_valid():
            form.save()
            product_name = form.cleaned_data.get("name")
            messages.success(request, f"{product_name} has been added")
            return redirect("dashboard:product")
    else:
        form = ProductForm()
    context = {
        "items": items,
        "form": form,
        "workers_count": workers_count,
        "orders_count": orders_count,
        "products_count": products_count,
    }
    return render(request, "dashboard/product.html", context)


@login_required
def product_update(request, pk):
    item = Product.objects.get(id=pk)
    if request.method == "POST":
        form = ProductForm(request.POST, instance=item)
        if form.is_valid():
            form.save()
            return redirect("dashboard:product")
    else:
        form = ProductForm(instance=item)
    context = {"form": form}
    return render(request, "dashboard/product_edit.html", context)


@login_required
def product_delete(request, pk):
    item = Product.objects.get(id=pk)
    if request.method == "POST":
        item.delete()
        return redirect("dashboard:product")
    return render(request, "dashboard/product_delete.html")


@login_required
def order(request):
    orders = Order.objects.all()
    orders_count = orders.count()
    workers_count = User.objects.all().count()
    products_count = Product.objects.all().count()
    context = {
        "orders": orders,
        "workers_count": workers_count,
        "orders_count": orders_count,
        "products_count": products_count,
    }
    return render(request, "dashboard/order.html", context)

inventoryproject/templates/dashboard/index.html
{% extends "partials/base.html" %}
{% block title %}Home page{% endblock %}
{% block content %}
{% if user.is_authenticated and user.is_staff and user.is_superuser %}
    {% include "partials/topnav.html" %}
    <div class="container">
        <div class="row my-5">
            <div class="col-md-6">
                <div class="bg-white">
                    <canvas id="myChart1" width="400" height="300"></canvas>
                    <script>
                        var ctx = document.getElementById('myChart1').getContext('2d');
                        var myChart1 = new Chart(ctx, {
                            type: 'pie',
                            data: {
                                labels: [{% for order in orders %} '{{ order.product.name }}' , {% endfor %}],
                                datasets: [{
                                    label: 'Orders',
                                    data: [{% for order in orders %} '{{ order.order_quantity }}' , {% endfor %}],
                                    backgroundColor: [
                                        'rgba(255, 99, 132, 1)',
                                        'rgba(54, 162, 235, 1)',
                                        'rgba(255, 206, 86, 1)',
                                        'rgba(75, 192, 192, 1)',
                                        'rgba(153, 102, 255, 1)',
                                        'rgba(25, 159, 64, 1)',
                                        'rgba(211, 99, 132, 1)',
                                        'rgba(234, 162, 235, 1)',
                                        'rgba(255, 206, 86, 1)',
                                        'rgba(34, 142, 192, 1)',
                                        'rgba(153, 102, 255, 1)',
                                        'rgba(255, 159, 64, 1)',
                                    ],
                                    borderColor: [
                                        'rgba(255, 99, 132, 1)',
                                        'rgba(54, 162, 235, 1)',
                                        'rgba(255, 206, 86, 1)',
                                        'rgba(75, 192, 192, 1)',
                                        'rgba(153, 102, 255, 1)',
                                        'rgba(255, 159, 64, 1)',
                                        'rgba(25, 159, 64, 1)',
                                        'rgba(211, 99, 132, 1)',
                                        'rgba(234, 162, 235, 1)',
                                        'rgba(255, 206, 86, 1)',
                                        'rgba(34, 142, 192, 1)',
                                        'rgba(153, 102, 255, 1)',
                                        'rgba(255, 159, 64, 1)',
                                    ],
                                    borderWidth: 1
                                }]
                            },
                            options: {
                                scales: {
                                    yAxes: [{
                                        ticks: {
                                            beginAtZero: true
                                        }
                                    }]
                                }
                            }
                        });
                    </script>
                </div>
            </div>
            <div class="col-md-6">
                <div class="bg-white">
                    <canvas id="myChart" width="400" height="300"></canvas>
                    <script>
                        var ctx = document.getElementById('myChart').getContext('2d');
                        var myChart = new Chart(ctx, {
                            type: 'bar',
                            data: {
                                labels: [{% for product in products %} '{{ product.name }}' , {% endfor %}],
                                datasets: [{
                                    label: 'Products',
                                    data: [{% for product in products %} {{ product.quantity }} , {% endfor %}],
                                    backgroundColor: [
                                        'rgba(75, 192, 192, 1)',
                                        'rgba(153, 102, 255, 1)',
                                        'rgba(25, 159, 64, 1)',
                                        'rgba(211, 99, 132, 1)',
                                        'rgba(234, 162, 235, 1)',
                                        'rgba(255, 206, 86, 1)',
                                        'rgba(34, 142, 192, 1)',
                                        'rgba(153, 102, 255, 1)',
                                        'rgba(255, 159, 64, 1)',
                                        'rgba(255, 99, 132, 1)',
                                        'rgba(54, 162, 235, 1)',
                                        'rgba(255, 206, 86, 1)',
                                        'rgba(75, 192, 192, 1)',
                                        'rgba(153, 102, 255, 1)',
                                        'rgba(255, 159, 64, 1)',
                                    ],
                                    borderColor: [
                                        'rgba(75, 192, 192, 1)',
                                        'rgba(153, 102, 255, 1)',
                                        'rgba(25, 159, 64, 1)',
                                        'rgba(211, 99, 132, 1)',
                                        'rgba(234, 162, 235, 1)',
                                        'rgba(255, 206, 86, 1)',
                                        'rgba(34, 142, 192, 1)',
                                        'rgba(153, 102, 255, 1)',
                                        'rgba(255, 159, 64, 1)',
                                        'rgba(255, 99, 132, 1)',
                                        'rgba(54, 162, 235, 1)',
                                        'rgba(255, 206, 86, 1)',
                                        'rgba(75, 192, 192, 1)',
                                        'rgba(153, 102, 255, 1)',
                                        'rgba(255, 159, 64, 1)',
                                    ],
                                    borderWidth: 1
                                }]
                            },
                            options: {
                                scales: {
                                    yAxes: [{
                                        ticks: {
                                            beginAtZero: true
                                        }
                                    }]
                                }
                            }
                        });
                    </script>
                </div>
            </div>
        </div>
    </div>
    {% else %}
    {% include "dashboard/staff_index.html" %}
    {% endif %}
{% endblock %}

inventoryproject/templates/dashboard/order.html
{% extends "partials/base.html" %}
{% block title %}Order page{% endblock %}
{% block content %}
    {% include "partials/topnav.html" %}
    <div class="container">
        <div class="row my-4">
            <div class="col-md-4">
            </div>
            <div class="col-md-8">
                <table class="table bg-white">
                    <thead class="bg-info">
                        <tr class="text-white">
                            <th scope="col">Product</th>
                            <th scope="col">Category</th>
                            <th scope="col">Quantity</th>
                            <th scope="col">Order by</th>
                            <th scope="col">Date</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for order in orders %}
                        <tr>
                            <td>{{ order.product.name }}</td>
                            <td>{{ order.product.category }}</td>
                            <td>{{ order.order_quantity }}</td>
                            <td>{{ order.staff.username }}</td>
                            <td>{{ order.date }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

inventoryproject/templates/dashboard/product.html
{% extends "partials/base.html" %}
{% block title %}Product page{% endblock %}
{% block content %}
{% load crispy_forms_tags %}
{% include "partials/topnav.html" %}
    <div class="container">
        <div class="row my-4">
            <div class="col-md-4">
                {% for message in messages %}
                {% if message %}
                <div class = "alert alert-{{ message.tags }}">
                    {{ message }}
                </div>
                {% endif %}
                {% endfor %}
                <div class="border bg-white p-3">
                    <h4>Add Products</h4>
                    <hr>
                    <form method="POST">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <input class="btn btn-success btn-block" type="submit" value="Add Product">
                    </form>
                </div>
            </div>
            <div class="col-md-8">
                <table class="table bg-white">
                    <thead class="bg-info">
                        <tr class="text-white">
                            <th scope="col">Name</th>
                            <th scope="col">Category</th>
                            <th scope="col">Quantity</th>
                            <th scope="col">Activity</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for item in items %}
                        <tr>
                            <td>{{ item.name }}</td>
                            <td>{{ item.category }}</td>
                            <td>{{ item.quantity }}</td>
                            <td>
                                <a class="btn btn-info btn-sm" href="{% url "dashboard:product_update" item.id %}">Edit</a>
                                <a class="btn btn-danger btn-sm" href="{% url "dashboard:product_delete" item.id %}">Delete</a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

inventoryproject/templates/dashboard/product_delete.html
{% extends 'partials/base.html' %}
{% block title %}Product Delete Page{% endblock %}
{% block content %}
<div class="row my-4">
    <div class="col-md-6 offset-md-3">
        <div class="border p-3 bg-white">
            <h3>Delete Item</h3>
            <hr>
            <form method="POST">
                <div class="alert alert-danger">
                    <h4>Are you sure, you want to delete?</h4>
                </div>
                {% csrf_token %}
                {{ form }}
                <a class="btn btn-secondary btn-sm" href="{% url 'dashboard:product' %}">Cancel</a>
                <input class="btn btn-danger btn-sm" type="submit" value="Confirm">
            </form>
        </div>
    </div>
</div>
{% endblock %}

inventoryproject/templates/dashboard/product_edit.html
{% extends 'partials/base.html' %}
{% block title %}Products Edit Page{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
<div class="row my-4">
    <div class="col-md-6 offset-md-3 p-3 bg-white">
        <h3>Edit Item</h3>
        <hr>
        <form method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <a class="btn btn-secondary" href="{% url "dashboard:product" %}">Cancel</a>
            <input class="btn btn-info" type="submit" value="Confirm">
        </form>
    </div>
</div>
{% endblock %}

inventoryproject/templates/dashboard/staff.html
{% extends "partials/base.html" %}
{% block title %}Staff page{% endblock %}
{% block content %}
{% include "partials/topnav.html" %}
    <div class="container">
        <div class="row my-4">
            <div class="col-md-4"></div>
            <div class="col-md-8">
                <table class="table bg-white">
                    <thead class="bg-info">
                        <tr class="text-white">
                            <th scope="col">#</th>
                            <th scope="col">Name</th>
                            <th scope="col">Email</th>
                            <th scope="col">Phone</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for worker in workers %}
                        <tr>
                            <th scope="row"><a class="btn btn-info btn-sm" href="{% url "dashboard:staff_detail" worker.pk %}">View</a></th>
                            <td>{{ worker.username }}</td>
                            <td>{{ worker.email }}</td>
                            <td>{{ worker.profile.phone }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

inventoryproject/templates/dashboard/staff_detail.html
{% extends "partials/base.html" %}
{% block title %}Staff Detail page{% endblock %}
{% block content %}
{% include "partials/topnav.html" %}
    <div class="container">
        <div class="row my-4">
            <div class="col-md-4">
            </div>
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header bg-info text-white">
                        Profile Page
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-8">
                                <span class="h4"> Profile Information</span>
                                <hr>
                                <table class="table bg-white table-borderless">
                                    <tbody>
                                        <tr>
                                            <th scope="row">Name</th>
                                            <td>{{ workers.username }}</td>
                                        </tr>
                                        <tr>
                                            <th scope="row">Email</th>
                                            <td>{{ workers.email }}</td>
                                        </tr>
                                        <tr>
                                            <th scope="row">Phone</th>
                                            <td>{{ workers.profile.phone }}</td>
                                        </tr>
                                        <tr>
                                            <th scope="row">Address</th>
                                            <td>{{ workers.profile.address }}</td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                            <div class="col-md-4">
                                <img class="img-thumbnail" src="{{ workers.profile.image.url }}" alt="profile-image">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

inventoryproject/templates/dashboard/staff_index.html
{% load crispy_forms_tags %}
<div>
    <div class="row mt-4">
        <div class="col-md-4">
            <div class="card">
                <div class="card-header">
                    Make Request
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <input class="btn btn-info btn-block" type="submit" value="Make Request">
                    </form>
                </div>
            </div>
        </div>
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    Orders Records
                </div>
                <div class="card-body">
                    <table class="table bg-white">
                        <thead class="bg-info text-white">
                            <tr>
                                <th scope="col">Product</th>
                                <th scope="col">Category</th>
                                <th scope="col">Quantity</th>
                                <th scope="col">Date</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for order in orders %}
                            {% if order.staff == user %}
                            <tr>
                                <td>{{ order.product.name }}</td>
                                <td>{{ order.product.category }}</td>
                                <td>{{ order.order_quantity }}</td>
                                <td>{{ order.date }}</td>
                            </tr>
                            {% endif %}
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>