inventoryproject/inventoryproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("dashboard/", include("dashboard.urls")),
    path("", include("user.urls")),
    path(
        "password_reset/",
        auth_views.PasswordResetView.as_view(template_name="user/password_reset.html"),
        name="password_reset",
    ),
    path(
        "password_reset_done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="user/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "password_reset_confirm/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="user/password_reset_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "password_reset_complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="user/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]

inventoryproject/user/urls.py
from django.urls import path
from . import views as user_views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

app_name = "user"
urlpatterns = [
    path("register/", user_views.register, name="register"),
    path("profile/", user_views.profile, name="profile"),
    path("profile/update/", user_views.profile_update, name="profile-update"),
    path(
        "", auth_views.LoginView.as_view(template_name="user/login.html"), name="login"
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(template_name="user/logout.html"),
        name="logout",
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inventoryproject/user/models.py
from django.db import models
from django.contrib.auth.models import User
class Profile (models.Model):
    staff = models.OneToOneField(User , on_delete=models.CASCADE , null=True)
    address = models.CharField(max_length=500 , null=True)
    phone = models.CharField(max_length=20 , null=True)
    image = models.ImageField(default='avatar.jpg' , upload_to='Profile_Images')
    def __str__(self):
        return f'{self.staff.username}-Profile'

inventoryproject/user/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile
class CreateUserForm(UserCreationForm):
    email = forms.EmailField()
    class Meta:
        model = User
        fields = ['username' , 'email' , 'password1' , 'password2']
class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username' , 'email']
class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['address' , 'phone' , 'image']

inventoryproject/user/views.py
from django.shortcuts import render , redirect
from .forms import CreateUserForm , UserUpdateForm , ProfileUpdateForm
from django.contrib import messages
def register(request):
    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request , f'Account has been created for {username}. continue to login')
            return redirect('user:login')
    else:
        form = CreateUserForm()
    context = {
        'form' : form
    }
    return render(request , 'user/register.html' , context)
def profile (request):
    return render(request , 'user/profile.html')
def profile_update (request):
    if request.method == 'POST':
        user_form = UserUpdateForm(request.POST , instance=request.user)
        profile_form = ProfileUpdateForm(request.POST , request.FILES , instance = request.user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            return redirect('user:profile')
    else:
        user_form = UserUpdateForm(instance=request.user)
        profile_form = ProfileUpdateForm(request.FILES , instance = request.user.profile)
    context = {
        'user_form' : user_form,
        'profile_form' : profile_form,
    }
    return render(request , 'user/profile_update.html' , context)

inventoryproject/templates/user/login.html
{% extends 'partials/base.html' %}
{% block title %}Login Page{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="row my-4">
        <div class="col-md-6 offset-md-3">
            {% for message in messages %}
                {% if message %}
                <div class = "alert alert-{{ message.tags }}">
                    {{ message }}
                </div>
                {% endif %}
            {% endfor %}
            <div class="border p-3 bg-white">
                <h4>Login Page</h4>
                <hr>
                <form method="POST">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <input class="btn btn-success" type="submit" value="Login">
                    <a class = "mx-4" href="{% url "password_reset" %}">Forget Password</a>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

inventoryproject/templates/user/logout.html
{% extends 'partials/base.html' %}
{% block title %}Logout Page{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="row my-4">
        <div class="col-md-6 offset-md-3">
            <div class="border p-3 bg-white">
                <h4>Logout Page</h4>
                <hr>
                <div class="alert alert-info">
                    <h5>You have been logged out</h5>
                </div>
                <a href="{% url 'user:login' %}">Login</a>
            </div>
        </div>
    </div>
{% endblock %}

inventoryproject/templates/user/password_reset.html
{% extends 'partials/base.html' %}
{% block title %}Password Reset Page{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="row my-4">
        <div class="col-md-6 offset-md-3">
            {% for message in messages %}
                {% if message %}
                <div class = "alert alert-{{ message.tags }}">
                    {{ message }}
                </div>
                {% endif %}
            {% endfor %}
            <div class="border p-3 bg-white">
                <h4>Password Reset Page</h4>
                <hr>
                <form method="POST">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <input class="btn btn-info" type="submit" value="Reset Password">
                </form>
            </div>
        </div>
    </div>
{% endblock %}

inventoryproject/templates/user/password_reset_complete.html
{% extends 'partials/base.html' %}
{% block title %}Password Reset Complete Page{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="row my-4">
        <div class="col-md-6 offset-md-3">
            <div class="border p-3 bg-white">
                <h4>Password Reset Complete Page</h4>
                <hr>
                <div class="alert alert-success">
                    <h5>Now You can log in with your new password</h5>
                </div>
                <a href="{% url 'user:login' %}">Login</a>
            </div>
        </div>
    </div>
{% endblock %}

inventoryproject/templates/user/password_reset_confirm.html
{% extends 'partials/base.html' %}
{% block title %}Password Reset Confirm Page{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="row my-4">
        <div class="col-md-6 offset-md-3">
            {% for message in messages %}
                {% if message %}
                <div class = "alert alert-{{ message.tags }}">
                    {{ message }}
                </div>
                {% endif %}
            {% endfor %}
            <div class="border p-3 bg-white">
                <h4>Password Reset Confirm Page</h4>
                <hr>
                <form method="POST">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <input class="btn btn-info" type="submit" value="Confirm Password">
                </form>
            </div>
        </div>
    </div>
{% endblock %}

inventoryproject/templates/user/password_reset_done.html
{% extends 'partials/base.html' %}
{% block title %}Password Reset Done Page{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="row my-4">
        <div class="col-md-6 offset-md-3">
            <div class="border p-3 bg-white">
                <h4>Password Reset Done Page</h4>
                <hr>
                <div class="alert alert-info">
                    <h5>A mail has been sent to the email address you provided. It has instructions you need to follow to reset your password</h5>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

inventoryproject/templates/user/profile.html
{% extends 'partials/base.html' %}
{% block title %}Profile Page{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="container">
        <div class="row my-4">
            <div class="col-md-4">
            </div>
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header bg-info text-white">
                        Profile Page
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-8">
                                <span class="h4"> Profile Information</span> <a class="btn btn-info btn-sm float-right"
                                    href="{% url "user:profile-update" %}">Edit</a>
                                <hr>
                                <table class="table bg-white table-borderless">
                                    <tbody>
                                        <tr>
                                            <th scope="row">Name</th>
                                            <td>{{ user.username }}</td>
                                        </tr>
                                        <tr>
                                            <th scope="row">Email</th>
                                            <td>{{ user.email }}</td>
                                        </tr>
                                        <tr>
                                            <th scope="row">Phone</th>
                                            <td>{{ user.profile.phone }}</td>
                                        </tr>
                                        <tr>
                                            <th scope="row">Address</th>
                                            <td>{{ user.profile.address }}</td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                            <div class="col-md-4">
                                <img class="img-thumbnail" src="{{ user.profile.image.url }}" alt="profile-image">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

inventoryproject/templates/user/profile_update.html
{% extends 'partials/base.html' %}
{% block title %}Profile Page{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="container">
        <div class="row my-4">
            <div class="col-md-4">
            </div>
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header bg-info text-white">
                        Profile Page
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-8">
                                <span class="h4"> Profile Information</span>
                                <hr>
                                <form method="post" enctype="multipart/form-data">
                                    {% csrf_token %}
                                    {{ user_form|crispy }}
                                    {{ profile_form|crispy }}
                                    <input class="btn btn-info" type="submit" value="Update">
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

inventoryproject/templates/user/register.html
{% extends "partials/base.html" %}
{% load crispy_forms_tags %}
{% block title %}Register Page{% endblock %}
{% block content %}
    <div class="row my-4">
        <div class="col-md-6 offset-md-3">
            <div class="border p-3 bg-white">
                <h4>Register Page</h4>
                <hr>
                <form method="POST">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <input class="btn btn-success" type="submit" value="Register">
                </form>
            </div>
        </div>
    </div>
{% endblock %}